### ISSUE TITLE
release 0.3 version to crates.io

### ISSUE THREAD

**Issue by hellow554** [fpagliughi/rust-industrial-io#8]
title says it all :)

**Comment by fpagliughi** [comment]
Hahaha. Yes, you're right. I forgot there were a bunch of updates that hadn't been released. I think there was some weirdness with the versioning of the underlying libiio, but I will check it, test, then publish the new release if it all looks OK.

But it's nice to know I'm not the only one using this crate!

**Comment by fpagliughi** [comment]
Let me know if you've tested the latest version and seen anything weird.

**Comment by hellow554** [comment]
I've used it to read channel properties so far, worked :)
My IIO driver doesn't allow me to use fancyer stuff, so that's what I'm stuck with, but that works :D

```
impl Input {
    pub fn new() -> Result<Self, IoError> {
        if let Some(dev) = Context::create_local()?
            .devices()
            .find(|d| d.name().as_deref() == Some(ADC_NAME))
        {
            Ok(Self { dev })
        } else {
            unimplemented!("Can't get analog input device") // TODO :)
        }
    }

    pub fn request(&mut self, channel: Channel) -> Result<f64, IoError> {
        let channelid = channel.idx();
        let factor = channel.factor();

        let channel = self.dev.get_channel(channelid)?;
        let raw = channel.attr_read_float("raw")?;
        let scale = channel.attr_read_float("scale")?;

        Ok(raw * scale * factor)
    }
}
```

that code works with latest master ☝️

**Comment by fpagliughi** [comment]
Done. Sorry for the delay.
